import sharp from 'sharp'
import { readdir, readFile, stat, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const IMAGES_DIR = path.join(ROOT, 'public', 'images')
const PLACEHOLDERS_FILE = path.join(ROOT, 'src', 'imagePlaceholders.ts')

const HERO_MAX_WIDTH = 1920
const HERO_QUALITY = 78
const PORTFOLIO_MAX_WIDTH = 1600
const PORTFOLIO_QUALITY = 75
const PLACEHOLDER_WIDTH = 24
const PLACEHOLDER_QUALITY = 40

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) yield* walk(full)
    else if (/\.jpe?g$/i.test(entry.name)) yield full
  }
}

const placeholders = {}
let totalBefore = 0
let totalAfter = 0

for await (const file of walk(IMAGES_DIR)) {
  const isHero = path.basename(path.dirname(file)) === 'hero'
  const maxWidth = isHero ? HERO_MAX_WIDTH : PORTFOLIO_MAX_WIDTH
  const quality = isHero ? HERO_QUALITY : PORTFOLIO_QUALITY

  const before = (await stat(file)).size
  const input = await readFile(file)

  const base = sharp(input).rotate().resize({ width: maxWidth, withoutEnlargement: true })
  const jpegBuffer = await base.clone().jpeg({ quality, mozjpeg: true }).toBuffer()
  const webpBuffer = await base.clone().webp({ quality }).toBuffer()
  const placeholderBuffer = await sharp(input)
    .rotate()
    .resize({ width: PLACEHOLDER_WIDTH })
    .webp({ quality: PLACEHOLDER_QUALITY })
    .toBuffer()

  const webpPath = file.replace(/\.jpe?g$/i, '.webp')
  await writeFile(file, jpegBuffer)
  await writeFile(webpPath, webpBuffer)

  const publicPath = '/' + path.relative(path.join(ROOT, 'public'), file).split(path.sep).join('/')
  placeholders[publicPath] = `data:image/webp;base64,${placeholderBuffer.toString('base64')}`

  const after = jpegBuffer.length + webpBuffer.length
  totalBefore += before
  totalAfter += after

  console.log(
    `${publicPath}: ${(before / 1024).toFixed(0)}KB -> jpeg ${(jpegBuffer.length / 1024).toFixed(0)}KB + webp ${(webpBuffer.length / 1024).toFixed(0)}KB`
  )
}

const placeholdersContent = `// Auto-generated by scripts/optimize-images.mjs - tiny blurred previews for blur-up loading
export const imagePlaceholders: Record<string, string> = ${JSON.stringify(placeholders, null, 2)}
`

await writeFile(PLACEHOLDERS_FILE, placeholdersContent)

console.log(`\nTotal: ${(totalBefore / 1024 / 1024).toFixed(1)}MB -> ${(totalAfter / 1024 / 1024).toFixed(1)}MB`)
